# Подключение библиотек NumPy

In [1]:
import numpy as np

# Методы создания массивов

In [2]:
arr1 = np.array([10, 20, 30, 40, 50])
print("Из списка:", arr1)

zeros = np.zeros(7)
print("Массив нулей:", zeros)

ones_2d = np.ones((3, 5))
print("Массив единиц 3×5:\n", ones_2d)

seq = np.arange(0, 30, 5)
print("arange(0, 30, 5):", seq)

Из списка: [10 20 30 40 50]
Массив нулей: [0. 0. 0. 0. 0. 0. 0.]
Массив единиц 3×5:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
arange(0, 30, 5): [ 0  5 10 15 20 25]


# Атрибуты массивов

In [3]:
print("Форма ones_2d:", ones_2d.shape)
print("Тип данных ones_2d:", ones_2d.dtype)
print("Форма seq:", seq.shape)
print("Тип данных seq:", seq.dtype)

Форма ones_2d: (3, 5)
Тип данных ones_2d: float64
Форма seq: (6,)
Тип данных seq: int64


# Работа с индексами и срезами

In [4]:
print("Первый элемент arr1:", arr1[0])
print("Последний элемент arr1:", arr1[-1])

print("Элементы arr1 со 2-го по 4-й:", arr1[1:4])

print("Элемент [1, 3] в ones_2d:", ones_2d[1, 3])

print("Подмассив 2×3 из ones_2d:\n", ones_2d[:2, 1:4])

Первый элемент arr1: 10
Последний элемент arr1: 50
Элементы arr1 со 2-го по 4-й: [20 30 40]
Элемент [1, 3] в ones_2d: 1.0
Подмассив 2×3 из ones_2d:
 [[1. 1. 1.]
 [1. 1. 1.]]


# Векторные операции и статистика

In [5]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("a + b :", a + b)
print("a * b :", a * b)
print("a в квадрате :", a ** 2)

print("Среднее значение a:", np.mean(a))
print("Сумма элементов a:", np.sum(a))
print("Минимум и максимум a:", np.min(a), "и", np.max(a))

a + b : [11 22 33 44 55]
a * b : [ 10  40  90 160 250]
a в квадрате : [ 1  4  9 16 25]
Среднее значение a: 3.0
Сумма элементов a: 15
Минимум и максимум a: 1 и 5
